version: "3.9"

services:
  notification-server:
    container_name: notification-server-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    env_file:
      - ./.env
    depends_on:
      - notification-db
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - notification_net

networks:
  notification_net:
    external: true
    name: notification_net

